
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: s11gabriel-external-secret
  namespace: s11gabriel

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore

  target:
    name: s11gabriel-app-secret
    creationPolicy: Owner

  data:
    - secretKey: fdfd
      remoteRef:
        key: s11gabriel/apps/apps
        property: fdfd
