apiVersion: external-secrets.io/v1
kind: SecretStore

metadata:
  name: vault-secret-store
  namespace: s11gabriel

spec:
  provider:
    vault:
      server: "https://vault-playground.edusuc.net"
      path: "Dev-secret"
      version: "v2"

      auth:
        tokenSecretRef:
          name: vault-token
          key: token
